[package]
name = 'awdb'
publish = false
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'awdb'

[dependencies]
extendr-api = { version = "0.7.1", features = ["serde"] }
rayon = "1.10.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
